listen:
  host: ""
  port: 7777
# referer host
verification: "www.example.invalid"
# MeiliSearch 密码至少16字节
meiliSearch:
  host: "172.17.0.1"
  apiKey: "${MEILI_MASTER_KEY}"
  port: 7700
# redis
redis:
  host: "172.17.0.1"
  password: "${REDIS_PASSWORD}"
  port: 6379
  db: 1
# email smtp
emailSmtp:
  smtp: "smtp.163.com"
  email: "dev@example.test"
  password: "${SMTP_PASSWORD}"
  port: 465
# database postgres
database:
  driverName: "postgres"
  host: "172.17.0.1"
  username: "postgres"
  password: "${POSTGRES_PASSWORD}"
  port: 5432
  baseName: "stellar_beacon"
# oss
oss:
  provider: "aliyun"
  endPoint: "https://oss-cn-shanghai.aliyuncs.com"
  region: "cn-shanghai"
  publicUrl: "http://i.example.invalid/"
  publicRead: false
  accessKeyID: "${ALIYUN_OSS_ACCESS_KEY_ID}"
  accessKeySecret: "${ALIYUN_OSS_ACCESS_KEY_SECRET}"
  bucketName: "example-bucket"
