listen:
  host: ""
  port: 7777
# referer host
verification: "localhost"
# MeiliSearch 密码至少16字节
meiliSearch:
  host: ""
  apiKey: ""
  port: 7700
# redis
redis:
  host: "127.0.0.1"
  password: "[REDACTED_SECRET]"
  port: 6379
  db: 1
# email smtp
email:
  smtp: ""
  email: ""
  password: ""
  port: 465
# database postgres
database:
  driverName: "postgres"
  host: ""
  username: ""
  password: ""
  port: 5432
  baseName: ""
# oss
oss:
  endPoint: ""
  accessKeyID: ""
  accessKeySecret: ""
  bucketName: ""