package port

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"
	"time"
)

// ReviewContentDigest is the stable, non-reversible identity of a generated
// review candidate. It is used to bind an approval to the exact text that was
// shown to the operator without persisting another copy of the content.
func ReviewContentDigest(content string) string {
	digest := sha256.Sum256([]byte(strings.TrimSpace(content)))
	return hex.EncodeToString(digest[:])
}

// ProviderProtocol identifies the wire protocol used by a model provider.
// These values are deliberately independent from any provider SDK.
type ProviderProtocol string

const (
	ProviderProtocolOpenAIResponses       ProviderProtocol = "openai_responses"
	ProviderProtocolAnthropicMessages     ProviderProtocol = "anthropic_messages"
	ProviderProtocolOpenAIChatCompletions ProviderProtocol = "openai_chat_completions"
)

// AIUseCase describes why a model is being called. Keeping use cases explicit
// prevents an embedding or moderation model from being silently reused for
// chat or writing.
type AIUseCase string

const (
	AIUseCaseChat       AIUseCase = "chat"
	AIUseCaseEmbedding  AIUseCase = "embedding"
	AIUseCaseVision     AIUseCase = "vision"
	AIUseCaseWriting    AIUseCase = "writing"
	AIUseCaseModeration AIUseCase = "moderation"
	AIUseCaseBehavior   AIUseCase = "behavior"
	AIUseCaseDream      AIUseCase = "dream"
)

// ChatRole is the provider-neutral role understood by the application.
type ChatRole string

const (
	ChatRoleSystem    ChatRole = "system"
	ChatRoleUser      ChatRole = "user"
	ChatRoleAssistant ChatRole = "assistant"
	ChatRoleTool      ChatRole = "tool"
)

// ChatMessagePartType identifies provider-neutral multimodal input parts.
// The application owns this small contract; Eino and provider-specific
// content block types must remain behind the infra adapter.
type ChatMessagePartType string

const (
	ChatMessagePartTypeText     ChatMessagePartType = "text"
	ChatMessagePartTypeImageURL ChatMessagePartType = "image_url"
)

// ChatMessagePart is an input part for a user message. Image URLs must be
// HTTP(S) URLs. Base64Data is raw standard base64 and is paired with MIMEType;
// neither value is ever included in structured logs.
type ChatMessagePart struct {
	Type       ChatMessagePartType `json:"type"`
	Text       string              `json:"text,omitempty"`
	URL        string              `json:"url,omitempty"`
	Base64Data string              `json:"base64Data,omitempty"`
	MIMEType   string              `json:"mimeType,omitempty"`
	Detail     string              `json:"detail,omitempty"`
}

type ChatMessage struct {
	Role         ChatRole
	Content      string
	ContentParts []ChatMessagePart `json:"contentParts,omitempty"`
	Name         string
	ToolCallID   string
	ToolCalls    []ToolCall
}

// ToolDefinition is a provider-neutral function tool declaration. Parameters
// contains a JSON Schema object; the infrastructure adapter translates it to
// the wire format required by the selected provider.
type ToolDefinition struct {
	Name        string
	Description string
	Parameters  json.RawMessage
}

type ToolChoice string

const (
	ToolChoiceAuto     ToolChoice = "auto"
	ToolChoiceNone     ToolChoice = "none"
	ToolChoiceRequired ToolChoice = "required"
)

// ToolCall is a model-produced function invocation. The application decides
// whether and how to execute it; a model adapter never executes tools.
type ToolCall struct {
	ID        string
	Name      string
	Arguments json.RawMessage
}

type StructuredOutputSpec struct {
	Name       string
	JSONSchema json.RawMessage
}

type ChatRequest struct {
	UseCase          AIUseCase
	Messages         []ChatMessage
	Model            string
	Temperature      *float32
	MaxOutputTokens  int
	Metadata         map[string]string
	StructuredOutput *StructuredOutputSpec
	Tools            []ToolDefinition
	ToolChoice       ToolChoice
}

type TokenUsage struct {
	InputTokens  int
	OutputTokens int
	TotalTokens  int
}

type ChatResponse struct {
	Text     string
	Provider string
	Protocol ProviderProtocol
	Model    string
	// RunID is generated by Benetnasch and remains stable across retries.
	RunID string
	// ProviderRunID is the provider-assigned request/response identifier, when
	// the protocol returns one. It must not replace RunID at our API boundary.
	ProviderRunID  string
	FinishReason   string
	Usage          TokenUsage
	ToolCalls      []ToolCall
	StructuredJSON json.RawMessage
	RepairAttempts int
}

type StreamEventKind string

const (
	StreamEventMeta     StreamEventKind = "meta"
	StreamEventDelta    StreamEventKind = "delta"
	StreamEventToolCall StreamEventKind = "tool_call"
	StreamEventCitation StreamEventKind = "citation"
	StreamEventState    StreamEventKind = "state"
	StreamEventDone     StreamEventKind = "done"
	StreamEventError    StreamEventKind = "error"
)

type Citation struct {
	DocumentID string `json:"documentId"`
	// ArticleID identifies the public source article. DocumentID/ChunkID can
	// identify the narrower retrieved fragment when the index is chunked.
	ArticleID int     `json:"articleId"`
	ChunkID   string  `json:"chunkId,omitempty"`
	Title     string  `json:"title"`
	URL       string  `json:"url,omitempty"`
	Score     float64 `json:"score,omitempty"`
}

type ChatStreamEvent struct {
	Kind     StreamEventKind
	RunID    string
	Provider string
	Protocol ProviderProtocol
	Model    string
	// ProviderRunID is populated when the provider exposes its identifier,
	// usually on the terminal event. RunID is always the stable local ID.
	ProviderRunID string
	Text          string
	ToolCalls     []ToolCall
	Citation      *Citation
	State         map[string]string
	Usage         *TokenUsage
}

// ChatGateway is the only chat contract application code should consume.
// Stream uses a callback so adapters can expose provider streaming without
// leaking an SDK-specific iterator or channel type.
type ChatGateway interface {
	Generate(context.Context, ChatRequest) (ChatResponse, error)
	Stream(context.Context, ChatRequest, func(ChatStreamEvent) error) error
}

type EmbeddingRequest struct {
	Inputs  []string
	Model   string
	Version string
}

type EmbeddingResult struct {
	Vectors   [][]float32
	Model     string
	Dimension int
	Version   string
}

type EmbeddingGateway interface {
	Embed(context.Context, EmbeddingRequest) (EmbeddingResult, error)
}

type ModelRoute struct {
	UseCase    AIUseCase
	Provider   string
	Protocol   ProviderProtocol
	Model      string
	DataPolicy string
}

// ModelRouter resolves a gateway by capability. Implementations may apply
// health checks and bounded fallback, but must never cross capability types.
type ModelRouter interface {
	ResolveChat(context.Context, AIUseCase) (ChatGateway, ModelRoute, error)
	ResolveEmbedding(context.Context, AIUseCase) (EmbeddingGateway, ModelRoute, error)
}

type ModelCapabilities struct {
	Generate         bool
	Streaming        bool
	Embedding        bool
	ToolCalls        bool
	StructuredOutput bool
}

type ModelProbeResult struct {
	Route             ModelRoute
	Capabilities      ModelCapabilities
	Reachable         bool
	Latency           time.Duration
	FirstTokenLatency time.Duration
	CheckedAt         time.Time
	ErrorCode         string
}

// ModelProbe performs an explicit, bounded connection/capability check. It is
// separate from ModelRouter so normal requests never incur probe traffic.
type ModelProbe interface {
	ProbeChat(context.Context, AIUseCase) (ModelProbeResult, error)
	ProbeEmbedding(context.Context) (ModelProbeResult, error)
}

type SearchMode string

const (
	SearchModeKeyword  SearchMode = "keyword"
	SearchModeHybrid   SearchMode = "hybrid"
	SearchModeSemantic SearchMode = "semantic"
)

type KnowledgeDocument struct {
	ID                 string
	Index              string
	Title              string
	Text               string
	URL                string
	Metadata           map[string]string
	Embedding          []float32
	EmbeddingModel     string
	EmbeddingVersion   string
	EmbeddingDimension int
}

const PublicArticleStatus = 1

// IsPublicArticle is the single visibility rule shared by lifecycle jobs,
// backfills, projectors, writers, and public search adapters. Callers must
// provide the current persisted status when it is available; event payloads
// are only hints and must not override this rule.
func IsPublicArticle(status, isDelete int) bool {
	return status == PublicArticleStatus && isDelete == 0
}

// ArticleChunkDocument is the provider-neutral schema for one searchable
// article chunk. It intentionally contains source/article metadata so later
// retrieval can return provenance without consulting PostgreSQL for every hit.
// Text cleaning and chunk boundary calculation belong to the indexing worker,
// not to this data contract.
type ArticleChunkDocument struct {
	ID              string    `json:"id"`
	ArticleID       int       `json:"articleId"`
	ArticleTitle    string    `json:"articleTitle"`
	Text            string    `json:"text"`
	Category        string    `json:"category"`
	Tags            []string  `json:"tags"`
	ArticleURL      string    `json:"articleUrl"`
	PublishedAt     time.Time `json:"publishedAt"`
	PublishedAtUnix int64     `json:"publishedAtUnix"`
	ChunkIndex      int       `json:"chunkIndex"`
	Status          int       `json:"status"`
	IsDelete        int       `json:"isDelete"`
}

func (d ArticleChunkDocument) IsPublic() bool {
	return IsPublicArticle(d.Status, d.IsDelete)
}

// IndexedArticleChunk is the complete write contract for the versioned
// article_chunks index. Keeping the vector metadata beside the source
// document prevents an adapter from guessing which model contract produced a
// vector.
type IndexedArticleChunk struct {
	Document           ArticleChunkDocument
	Embedding          []float32
	EmbeddingModel     string
	EmbeddingVersion   string
	EmbeddingDimension int
}

// ArticleChunkIndex owns the article_chunks projection. DeleteArticle is
// deliberately article-scoped: a hard-deleted article no longer provides its
// old chunk count, so deleting by a guessed list of chunk IDs would leave
// stale searchable documents behind.
type ArticleChunkIndex interface {
	UpsertChunks(context.Context, []IndexedArticleChunk) error
	DeleteArticle(context.Context, int) error
}

type KnowledgeQuery struct {
	Index         string
	Query         string
	Mode          SearchMode
	SemanticRatio float32
	Limit         int
	Filter        KnowledgeFilter
}

const (
	DefaultKnowledgeSearchLimit = 20
	MaxKnowledgeSearchLimit     = 100
	DefaultSemanticRatio        = float32(0.65)
)

type KnowledgeHit struct {
	Index      string
	ID         string
	Title      string
	Text       string
	URL        string
	Score      float64
	Highlights map[string]string
	Metadata   map[string]string
}

// KnowledgeIndex abstracts keyword, semantic and hybrid retrieval. The
// Meilisearch adapter belongs in infra and must not appear in this package.
type KnowledgeIndex interface {
	Upsert(context.Context, []KnowledgeDocument) error
	Delete(context.Context, []string) error
	Search(context.Context, KnowledgeQuery) ([]KnowledgeHit, error)
}

// KnowledgeSearcher is the read side of KnowledgeIndex. Keeping it separate
// lets the public article search path depend only on search capabilities while
// indexing and deletion remain owned by their lifecycle worker.
type KnowledgeSearcher interface {
	Search(context.Context, KnowledgeQuery) ([]KnowledgeHit, error)
}

type AIJobStatus string

const (
	AIJobPending   AIJobStatus = "pending"
	AIJobRunning   AIJobStatus = "running"
	AIJobSucceeded AIJobStatus = "succeeded"
	AIJobFailed    AIJobStatus = "failed"
	AIJobDead      AIJobStatus = "dead"
)

const DefaultAIJobMaxAttempts = 3

type AIJob struct {
	ID             string
	Kind           string
	IdempotencyKey string
	Payload        []byte
	Status         AIJobStatus
	Attempts       int
	MaxAttempts    int
	RunAfter       time.Time
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AIJobResult struct {
	RunID   string
	Payload []byte
}

// AIJobRepository is a durable queue contract. Claim must be lease-based and
// implementations must make IdempotencyKey unique at the persistence layer.
type AIJobRepository interface {
	Enqueue(context.Context, AIJob) error
	Claim(context.Context, string, time.Time, time.Duration) (AIJob, bool, error)
	Complete(context.Context, string, string, AIJobResult) error
	Retry(context.Context, string, string, time.Time, string) error
	DeadLetter(context.Context, string, string, string) error
}

// AIJobKindClaimer is an optional refinement implemented by the durable
// PostgreSQL queue. It prevents workers for different capabilities from
// stealing and dead-lettering one another's jobs while keeping the basic
// queue contract usable by small in-memory test fakes.
type AIJobKindClaimer interface {
	ClaimKind(context.Context, string, string, time.Time, time.Duration) (AIJob, bool, error)
}

func ClaimAIJob(ctx context.Context, jobs AIJobRepository, workerID, kind string, now time.Time, lease time.Duration) (AIJob, bool, error) {
	if typed, ok := jobs.(AIJobKindClaimer); ok {
		return typed.ClaimKind(ctx, workerID, kind, now, lease)
	}
	return jobs.Claim(ctx, workerID, now, lease)
}

type ReviewStatus string

const (
	ReviewPending           ReviewStatus = "pending"
	ReviewApproved          ReviewStatus = "approved"
	ReviewPartiallyApproved ReviewStatus = "partially_approved"
	ReviewRejected          ReviewStatus = "rejected"
	ReviewExpired           ReviewStatus = "expired"
)

type ReviewActionType string

const (
	ReviewActionCreated           ReviewActionType = "created"
	ReviewActionAccepted          ReviewActionType = "accepted"
	ReviewActionPartiallyAccepted ReviewActionType = "partially_accepted"
	ReviewActionRejected          ReviewActionType = "rejected"
	ReviewActionRegenerated       ReviewActionType = "regenerated"
	ReviewActionExpired           ReviewActionType = "expired"
	ReviewActionPublished         ReviewActionType = "published"
	ReviewActionPublishFailed     ReviewActionType = "publish_failed"
)

func NormalizeReviewAction(value string) (ReviewActionType, error) {
	action := ReviewActionType(strings.ToLower(strings.TrimSpace(value)))
	switch action {
	case ReviewActionCreated,
		ReviewActionAccepted,
		ReviewActionPartiallyAccepted,
		ReviewActionRejected,
		ReviewActionRegenerated,
		ReviewActionExpired,
		ReviewActionPublished,
		ReviewActionPublishFailed:
		return action, nil
	default:
		return "", errors.New("review action is invalid")
	}
}

type ReviewPublishStatus string

const (
	ReviewPublishNotAttempted ReviewPublishStatus = "not_attempted"
	ReviewPublishProcessing   ReviewPublishStatus = "processing"
	ReviewPublishSucceeded    ReviewPublishStatus = "succeeded"
	ReviewPublishSkipped      ReviewPublishStatus = "skipped"
	ReviewPublishFailed       ReviewPublishStatus = "failed"
)

func NormalizeReviewPublishStatus(value string) (ReviewPublishStatus, error) {
	status := ReviewPublishStatus(strings.ToLower(strings.TrimSpace(value)))
	switch status {
	case ReviewPublishNotAttempted, ReviewPublishProcessing, ReviewPublishSucceeded, ReviewPublishSkipped, ReviewPublishFailed:
		return status, nil
	default:
		return "", errors.New("review publish status is invalid")
	}
}

type AIReview struct {
	ID         string
	TargetType string
	TargetID   string
	// SessionID binds a review to the authenticated/agent session that
	// created it. It is optional for legacy autonomous reviews, but when set
	// every subsequent action must carry the same binding.
	SessionID          string
	ContentDigest      string
	BoundAt            time.Time
	Operation          string
	Content            string
	Diff               string
	Status             ReviewStatus
	RunID              string
	ReviewerID         string
	AgentID            string
	PromptVersion      string
	SourceArticleID    int
	IdempotencyKey     string
	RejectReason       string
	PublishStatus      ReviewPublishStatus
	PublishError       string
	PublishedContentID string
	PublicationKey     string
	PublishedAt        time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	ExpiresAt          time.Time
}

type AIReviewAction struct {
	ID             string
	ReviewID       string
	SessionID      string
	TargetType     string
	TargetID       string
	ContentDigest  string
	ExpiresAt      time.Time
	Action         ReviewActionType
	ActorID        string
	Content        string
	RunID          string
	IdempotencyKey string
	CreatedAt      time.Time
}

type ReviewFilter struct {
	Status     ReviewStatus
	TargetType string
	TargetID   string
	Operation  string
	AgentID    string
	From       time.Time
	To         time.Time
	Current    int
	Size       int
}

type AIReviewRepository interface {
	Create(context.Context, AIReview) error
	Get(context.Context, string) (AIReview, error)
	List(context.Context, ReviewFilter) ([]AIReview, int, error)
	ApplyAction(context.Context, string, AIReviewAction) error
	Approve(context.Context, string, string) error
	Reject(context.Context, string, string, string) error
	Expire(context.Context, time.Time) (int, error)
}

// AIReviewPublication records the outcome of an approved review's external
// publication. Publication is performed by an application service first; the
// repository then atomically records the decision and outcome for audit.
type AIReviewPublication struct {
	Status         ReviewPublishStatus
	ContentID      string
	PublicationKey string
	PublishedAt    time.Time
}

// AIReviewPublicationRepository is an optional refinement implemented by the
// durable review repository. Keeping it separate preserves compatibility with
// small fakes and with old read-only review adapters.
type AIReviewPublicationRepository interface {
	FinalizePublication(context.Context, string, AIReviewAction, AIReviewPublication) error
	RecordPublicationFailure(context.Context, string, AIReviewAction, string) error
	ExpireOne(context.Context, string, string, time.Time) error
}

// AIReviewPublicationClaimRepository closes the check-then-publish race. A
// concrete repository atomically moves a pending review to processing and
// returns false when another request already owns the publication attempt.
// The separate interface keeps small read-only/test adapters source
// compatible; production publication repositories should implement it.
type AIReviewPublicationClaimRepository interface {
	ClaimPublication(context.Context, string, AIReviewAction) (bool, error)
}

type LifeStage string

const (
	LifeStageNewborn   LifeStage = "newborn"
	LifeStageGrowing   LifeStage = "growing"
	LifeStageSettled   LifeStage = "settled"
	LifeStageForgotten LifeStage = "forgotten"
)

type AgentProfile struct {
	ID              string
	Name            string
	PromptVersion   string
	SystemPromptRef string
	// SystemPrompt and Opening are kept in the profile port so a profile can
	// be versioned and tested without making the application know where the
	// prompt is stored (configuration, a database, or a future control plane).
	SystemPrompt    string
	Opening         string
	RhythmPrompts   map[AgentRhythmPhase]string
	BehaviorEnabled bool
	Enabled         bool
	UpdatedAt       time.Time
}

type AgentProfileRepository interface {
	Get(context.Context, string) (AgentProfile, error)
	Save(context.Context, AgentProfile) error
}

type AgentActivity struct {
	ID          string
	Kind        string
	Emotion     string
	ContentType string
	ContentID   string
	LifeStage   LifeStage
	Metadata    map[string]string
	OccurredAt  time.Time
}

type AgentActivityFilter struct {
	Kind      string
	LifeStage LifeStage
	From      time.Time
	To        time.Time
	Limit     int
}

type AgentActivityRepository interface {
	Append(context.Context, AgentActivity) error
	List(context.Context, AgentActivityFilter) ([]AgentActivity, error)
}

type AIRunStatus string

const (
	AIRunStarted   AIRunStatus = "started"
	AIRunSucceeded AIRunStatus = "succeeded"
	AIRunFailed    AIRunStatus = "failed"
	AIRunCanceled  AIRunStatus = "canceled"
)

type AgentRun struct {
	ID                string
	RequestID         string
	UseCase           AIUseCase
	Provider          string
	Protocol          ProviderProtocol
	Model             string
	ProviderRunID     string
	Status            AIRunStatus
	Usage             TokenUsage
	FirstTokenAt      time.Time
	FirstTokenLatency time.Duration
	StartedAt         time.Time
	CompletedAt       time.Time
	Duration          time.Duration
	ErrorCode         string
	SanitizedError    string
}

// AIRunObserver receives a final, sanitized snapshot of each provider call.
// Observers must not make the provider call depend on durable observability;
// an observer failure is therefore represented by its own implementation and
// cannot be returned through this contract.
type AIRunObserver interface {
	ObserveAIRun(context.Context, AgentRun)
}

type AgentRunFilter struct {
	UseCase AIUseCase
	Status  AIRunStatus
	Current int
	Size    int
}

type AgentRunRepository interface {
	Start(context.Context, AgentRun) error
	Complete(context.Context, string, AgentRun) error
	Fail(context.Context, string, AgentRun) error
	List(context.Context, AgentRunFilter) ([]AgentRun, int, error)
}
