package httpapi

import (
	api "github.com/eternallyzzz/stellar-beacon/internal/interfaces/http/handlers"
	"net/http"

	appruntime "github.com/eternallyzzz/stellar-beacon/internal/infrastructure/runtime"
	"github.com/gin-gonic/gin"
)

// RouterSetup registers the versioned HTTP surface. The reverse proxy removes
// the external /api prefix, so the backend intentionally owns /v1 only.
func RouterSetup(router *gin.Engine) {
	router.GET("/healthz", func(c *gin.Context) {
		c.Status(http.StatusOK)
	})
	router.GET("/readyz", func(c *gin.Context) {
		state := appruntime.Snapshot()
		if !state.Ready {
			c.JSON(http.StatusServiceUnavailable, state)
			return
		}
		c.JSON(http.StatusOK, state)
	})
	router.GET("/articles/:articleId", api.RenderArticleSEO)
	router.GET("/sitemap.xml", api.RenderSitemap)
	router.GET("/robots.txt", api.RenderRobots)
	router.GET("/feed.xml", api.RenderFeed)

	v1 := router.Group("/v1")
	public := v1.Group("/public")
	auth := v1.Group("/auth")
	admin := v1.Group("/admin")

	articles := public.Group("/articles")
	articles.GET("/featured", api.ListTopAndFeaturedArticles)
	articles.GET("", api.ListArticles)
	articles.GET("/by-category", api.GetArticlesByCategoryId)
	articles.GET("/:articleId", api.GetArticleById)
	articles.POST("/:articleId/access", api.AccessArticle)
	articles.POST("/:articleId/read-sessions", api.TrackArticleReadSession)
	articles.POST("/:articleId/continuation-events", api.TrackArticleContinuationEvent)
	articles.GET("/by-tag", api.ListArticlesByTagId)
	articles.GET("/search", api.ListArticlesBySearch)
	public.GET("/archives", api.ListArchives)
	public.GET("/", api.GetBlogHomeInfo)
	public.GET("/about", api.GetAbout)
	public.POST("/reports/visit", api.Report)
	public.POST("/subscriptions", api.SubscribeNewsletter)
	public.POST("/subscriptions/confirm", api.ConfirmNewsletter)
	public.POST("/subscriptions/unsubscribe", api.UnsubscribeNewsletter)
	public.POST("/growth/events", api.TrackGrowthEvent)
	public.GET("/categories", api.ListCategories)
	public.GET("/links", api.ListFriendLinks)
	public.POST("/links/applications", api.ApplyFriendLink)
	public.GET("/series", api.ListPublicSeries)
	public.GET("/series/:seriesId", api.GetPublicSeries)
	public.GET("/albums", api.ListPhotoAlbums)
	public.GET("/albums/:albumId/photos", api.ListPhotosByAlbumId)
	public.GET("/tags", api.GetAllTags)
	public.GET("/tags/top", api.GetTopTenTags)
	public.GET("/talks", api.ListTalks)
	public.GET("/talks/:talkId", api.GetTalkById)
	public.GET("/users/:userInfoId", api.GetUserInfoById)
	public.GET("/feed", api.PlatformFeed)
	public.GET("/authors", api.ListPlatformAuthors)
	public.GET("/authors/:handle", api.GetAuthor)
	public.GET("/authors/:handle/articles", api.ListAuthorArticles)
	public.GET("/authors/:handle/talks", api.ListAuthorTalks)
	public.GET("/authors/:handle/series", api.ListAuthorSeries)
	public.GET("/topics/:topic/:slug/articles", api.ListTopicArticles)
	public.GET("/media/proxy", api.ProxyMedia)
	public.GET("/diagnostics/business-error", api.HandleBizException)

	comments := public.Group("/comments")
	comments.POST("", api.SaveComment)
	comments.GET("", api.GetComments)
	comments.GET("/top", api.ListTopSixComments)
	comments.GET("/:commentId/replies", api.ListRepliesByCommentId)

	studio := v1.Group("/studio")
	studio.GET("/dashboard", api.StudioDashboard)
	studio.PUT("/profile", api.UpdateStudioProfile)
	studio.GET("/articles", api.ListStudioArticles)
	studio.GET("/articles/:articleId", api.GetStudioArticle)
	studio.POST("/articles", api.SaveStudioArticle)
	studio.PUT("/articles/:articleId", api.SaveStudioArticle)
	studio.DELETE("/articles", api.DeleteStudioArticles)
	studio.GET("/talks", api.ListStudioTalks)
	studio.GET("/talks/:talkId", api.GetStudioTalk)
	studio.POST("/talks", api.SaveStudioTalk)
	studio.PUT("/talks/:talkId", api.SaveStudioTalk)
	studio.DELETE("/talks", api.DeleteStudioTalks)
	studio.GET("/series", api.ListStudioSeries)
	studio.GET("/series/:seriesId", api.GetStudioSeries)
	studio.POST("/series", api.SaveStudioSeries)
	studio.PUT("/series/:seriesId", api.SaveStudioSeries)
	studio.DELETE("/series/:seriesId", api.DeleteStudioSeries)
	studio.GET("/categories", api.ListStudioCategories)
	studio.POST("/categories", api.SaveStudioCategory)
	studio.PUT("/categories/:categoryId", api.SaveStudioCategory)
	studio.DELETE("/categories/:categoryId", api.DeleteStudioCategory)
	studio.GET("/tags", api.ListStudioTags)
	studio.POST("/tags", api.SaveStudioTag)
	studio.PUT("/tags/:tagId", api.SaveStudioTag)
	studio.DELETE("/tags/:tagId", api.DeleteStudioTag)
	studio.POST("/uploads", api.UploadStudioAsset)
	auth.GET("/verification-code", api.SendCode)
	auth.POST("/register", api.Register)
	auth.PUT("/password", api.UpdatePassword)
	auth.POST("/logout", api.Logout)
	auth.PUT("/me", api.UpdateUserInfo)
	auth.POST("/me/avatar", api.UpdateUserAvatar)
	auth.PUT("/me/email", api.SaveUserEmail)
	auth.PUT("/me/subscription", api.UpdateUserSubscribe)
	auth.PUT("/me/notifications", api.UpdateUserCommentNotice)
	auth.PUT("/me/reactions", api.ToggleArticleReaction)
	auth.GET("/me/reactions", api.ListMyArticleReactions)
	auth.GET("/me/reactions/state", api.ListArticleReactionStates)

	admin.PUT("/content/:type/:id/moderation", api.ModerateContent)
	admin.PUT("/content/articles/:articleId/distribution", api.DistributeArticle)
	admin.GET("/dashboard", api.GetBlogBackInfo)
	admin.GET("/dashboard/analytics", api.GetDashboardAnalytics)
	admin.GET("/content/analytics", api.GetContentAnalytics)
	admin.GET("/content/analytics/articles", api.ListContentAnalyticsArticles)
	admin.GET("/content/analytics/articles/:articleId", api.GetContentAnalyticsArticle)
	admin.GET("/content/analytics/continuation-targets", api.ListContentContinuationTargets)
	admin.GET("/growth/summary", api.GetGrowthSummary)
	admin.GET("/newsletter/health", api.GetNewsletterHealth)
	admin.GET("/newsletter/subscribers", api.ListNewsletterSubscribers)
	admin.PUT("/newsletter/subscribers/status", api.UpdateNewsletterSubscriberStatus)
	admin.POST("/newsletter/subscribers/:subscriberId/resend", api.ResendNewsletterConfirmation)
	admin.GET("/newsletter/deliveries", api.ListNewsletterDeliveries)
	admin.POST("/newsletter/deliveries/retry", api.RetryNewsletterDelivery)
	admin.POST("/newsletter/deliveries/retry-failed", api.RetryFailedNewsletterDeliveries)
	admin.GET("/media", api.ListMedia)
	admin.POST("/media/upload", api.UploadMedia)
	admin.DELETE("/media", api.DeleteMedia)
	admin.GET("/articles", api.ListArticlesAdmin)
	admin.POST("/articles", api.SaveOrUpdateArticle)
	admin.GET("/articles/:articleId", api.GetArticleBackById)
	admin.PUT("/articles/featured", api.UpdateArticleTopAndFeatured)
	admin.PUT("/articles/trash", api.UpdateArticleDelete)
	admin.DELETE("/articles/batch-delete", api.DeleteArticles)
	admin.POST("/articles/images", api.SaveArticleImages)
	admin.POST("/articles/import", api.ImportArticles)
	admin.POST("/articles/export", api.ExportArticles)

	admin.GET("/site", api.GetWebsiteConfig)
	admin.PUT("/site", api.UpdateWebsiteConfig)
	admin.PUT("/about", api.UpdateAbout)
	admin.POST("/site/images", api.SaveBlogPhotoAlbumCover)

	admin.GET("/categories", api.ListCategoriesAdmin)
	admin.GET("/categories/search", api.ListCategoriesAdminBySearch)
	admin.DELETE("/categories", api.DeleteCategories)
	admin.POST("/categories", api.SaveOrUpdateCategory)
	admin.GET("/series", api.ListAdminSeries)
	admin.POST("/series", api.SaveOrUpdateSeries)
	admin.DELETE("/series", api.DeleteSeries)
	admin.GET("/series/options", api.ListSeriesOptions)
	admin.GET("/tags", api.ListTagsAdmin)
	admin.GET("/tags/search", api.ListTagsAdminBySearch)
	admin.POST("/tags", api.SaveOrUpdateTag)
	admin.DELETE("/tags", api.DeleteTag)

	admin.GET("/comments", api.ListCommentBackDTO)
	admin.PUT("/comments/review", api.UpdateCommentsReview)
	admin.DELETE("/comments", api.DeleteComments)
	admin.GET("/friend-links", api.ListFriendLinkDTO)
	admin.POST("/friend-links", api.SaveOrUpdateFriendLink)
	admin.PUT("/friend-links/review", api.ReviewFriendLinks)
	admin.DELETE("/friend-links", api.DeleteFriendLink)

	admin.POST("/albums/cover", api.SavePhotoAlbumCover)
	admin.POST("/albums", api.SaveOrUpdatePhotoAlbum)
	admin.GET("/albums", api.ListPhotoAlbumBacks)
	admin.GET("/albums/options", api.ListPhotoAlbumBackInfos)
	admin.GET("/albums/:albumId", api.GetPhotoAlbumBackById)
	admin.DELETE("/albums/:albumId", api.DeletePhotoAlbumById)
	admin.POST("/photos/upload", api.SavePhotosAlbumCover)
	admin.GET("/photos", api.ListPhotos)
	admin.PUT("/photos", api.UpdatePhoto)
	admin.POST("/photos", api.SavePhotos)
	admin.PUT("/photos/album", api.UpdatePhotosAlbum)
	admin.PUT("/photos/trash", api.UpdatePhotoDelete)
	admin.DELETE("/photos", api.DeletePhotos)

	admin.POST("/talks/images", api.SaveTalkImages)
	admin.POST("/talks", api.SaveOrUpdateTalk)
	admin.DELETE("/talks", api.DeleteTalks)
	admin.GET("/talks", api.ListBackTalks)
	admin.GET("/talks/:talkId", api.GetBackTalkById)

	admin.GET("/permissions", api.ListResources)
	admin.DELETE("/permissions/:resourceId", api.DeleteResource)
	admin.POST("/permissions", api.SaveOrUpdateResource)
	admin.GET("/roles/resource-options", api.ListResourceOption)
	admin.GET("/users/roles", api.ListUserRoles)
	admin.GET("/roles", api.ListRoles)
	admin.POST("/roles", api.SaveOrUpdateRole)
	admin.DELETE("/roles", api.DeleteRoles)
	admin.GET("/roles/menu-options", api.ListMenuOptions)
	admin.GET("/menus", api.ListMenus)
	admin.POST("/menus", api.SaveOrUpdateMenu)
	admin.PUT("/menus/:menuId/visibility", api.UpdateMenuIsHidden)
	admin.DELETE("/menus/:menuId", api.DeleteMenu)
	admin.GET("/me/menu", api.ListUserMenus)

	admin.GET("/users/areas", api.ListUserAreas)
	admin.GET("/users", api.ListUsers)
	admin.PUT("/users/password", api.UpdateAdminPassword)
	admin.PUT("/users/roles", api.UpdateUserRole)
	admin.PUT("/users/disable", api.UpdateUserDisable)
	admin.GET("/users/online", api.ListOnlineUsers)
	admin.DELETE("/users/:userInfoId/online", api.RemoveOnlineUser)

	admin.POST("/jobs", api.SaveJob)
	admin.PUT("/jobs", api.UpdateJob)
	admin.DELETE("/jobs", api.DeleteJobById)
	admin.GET("/jobs/:id", api.GetJobById)
	admin.GET("/jobs", api.ListJobs)
	admin.PUT("/jobs/status", api.UpdateJobStatus)
	admin.PUT("/jobs/run", api.RunJob)
	admin.GET("/jobs/groups", api.ListJobGroup)
	admin.GET("/jobs/targets", api.ListJobTargets)
	admin.GET("/logs/jobs", api.ListJobLogs)
	admin.DELETE("/logs/jobs", api.DeleteJobLogs)
	admin.DELETE("/logs/jobs/clean", api.CleanJobLogs)
	admin.GET("/logs/jobs/groups", api.ListJobLogGroups)
	admin.GET("/logs/operations", api.ListOperationLogs)
	admin.DELETE("/logs/operations", api.DeleteOperationLogs)
	admin.GET("/logs/exceptions", api.ListErrorLogs)
	admin.DELETE("/logs/exceptions", api.DeleteErrorLogs)
}
